{
 "title": "Wifi Bandung Juara",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "lokasi",
    "label": "nama_lokasi",
    "query": "SELECT nama_lokasi FROM wifiBandung"
   }
  ]
 },
 "panels": [
  {
   "title": "Tren Pengguna Per Lokasi [ $lokasi ]",
   "type": "bargauge",
   "description": "Selama tahun 2017\n(Biru = diatas rata-rata)",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "org" } },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT January AS 'JAN' FROM wifiBandung WHERE nama_lokasi LIKE '$lokasi'; "
    },
    {
     "rawSql": "SELECT February AS 'FEB' FROM wifiBandung  WHERE nama_lokasi LIKE '$lokasi'; "
    },
    {
     "rawSql": "SELECT March AS 'MAR' FROM wifiBandung WHERE nama_lokasi LIKE '$lokasi'; "
    },
    {
     "rawSql": "SELECT April AS 'APR' FROM wifiBandung WHERE nama_lokasi LIKE '$lokasi'; "
    },
    {
     "rawSql": "SELECT May AS 'MAY' FROM wifiBandung WHERE nama_lokasi LIKE '$lokasi'; "
    },
    {
     "rawSql": "SELECT June AS 'JUN' FROM wifiBandung WHERE nama_lokasi LIKE '$lokasi'; "
    },
    {
     "rawSql": "SELECT July AS 'JUL' FROM wifiBandung WHERE nama_lokasi LIKE '$lokasi'; "
    },
    {
     "rawSql": "SELECT August AS 'AUG' FROM wifiBandung WHERE nama_lokasi LIKE '$lokasi'; "
    },
    {
     "rawSql": "SELECT September AS 'SEP' FROM wifiBandung WHERE nama_lokasi LIKE '$lokasi'; "
    },
    {
     "rawSql": "SELECT October AS 'OCT' FROM wifiBandung WHERE nama_lokasi LIKE '$lokasi'; "
    },
    {
     "rawSql": "SELECT November AS 'NOV' FROM wifiBandung WHERE nama_lokasi LIKE '$lokasi'; "
    },
    {
     "rawSql": "SELECT December AS 'DES' FROM wifiBandung WHERE nama_lokasi LIKE '$lokasi'; "
    }
   ]
  },
  {
   "title": "Total Pengguna Per Lokasi [ $lokasi ]",
   "type": "stat",
   "description": "Selama tahun 2017",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "org" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT grand_total FROM wifiBandung WHERE nama_lokasi LIKE '$lokasi'; "
    }
   ]
  },
  { "title": "Total Pengguna", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Total Pengguna Wifi Bandung Juara ",
   "type": "stat",
   "description": "Selama tahun 2017",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "org" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(grand_total) FROM wifiBandung; "
    }
   ]
  },
  {
   "title": "Total Pengguna Wifi (Kategori Desa)",
   "type": "stat",
   "description": "Selama tahun 2017",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "org" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(grand_total) FROM wifiBandung WHERE deskripsi LIKE 'Kecamatan%'; "
    }
   ]
  },
  {
   "title": "Total Pengguna Wifi (Kategori Masjid)",
   "type": "stat",
   "description": "Selama tahun 2017",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "org" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(grand_total) FROM wifiBandung WHERE nama_lokasi LIKE 'Masjid%'; "
    }
   ]
  },
  {
   "title": "Total Pengguna Bulanan",
   "type": "stat",
   "description": "Selama tahun 2017\n(Biru = diatas rata-rata)",
   "gridPos": { "h": 14, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "org" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(January) AS 'JAN' FROM wifiBandung; "
    },
    {
     "rawSql": "SELECT SUM(February) AS 'FEB' FROM wifiBandung; "
    },
    {
     "rawSql": "SELECT SUM(March) AS 'MAR' FROM wifiBandung; "
    },
    {
     "rawSql": "SELECT SUM(April) AS 'APR' FROM wifiBandung; "
    },
    {
     "rawSql": "SELECT SUM(May) AS 'MAY' FROM wifiBandung; "
    },
    {
     "rawSql": "SELECT SUM(June) AS 'JUN' FROM wifiBandung; "
    },
    {
     "rawSql": "SELECT SUM(July) AS 'JUL' FROM wifiBandung; "
    },
    {
     "rawSql": "SELECT SUM(August) AS 'AUG' FROM wifiBandung; "
    },
    {
     "rawSql": "SELECT SUM(September) AS 'SEP' FROM wifiBandung; "
    },
    {
     "rawSql": "SELECT SUM(October) AS 'OCT' FROM wifiBandung; "
    },
    {
     "rawSql": "SELECT SUM(November) AS 'NOV' FROM wifiBandung; "
    },
    {
     "rawSql": "SELECT SUM(December) AS 'DES' FROM wifiBandung; "
    }
   ]
  },
  {
   "title": "Total Pengguna Wifi (Kategori Taman)",
   "type": "stat",
   "description": "Selama tahun 2017",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "org" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(grand_total) FROM wifiBandung WHERE nama_lokasi LIKE 'Taman%'; "
    }
   ]
  },
  {
   "title": "Total Pengguna Wifi (Kategori Lainnya)",
   "type": "stat",
   "description": "Selama tahun 2017",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "org" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(grand_total) FROM wifiBandung WHERE nama_lokasi NOT LIKE 'Taman%' \nAND nama_lokasi NOT LIKE 'Masjid%' \nAND deskripsi NOT LIKE 'Kecamatan%';"
    }
   ]
  },
  {
   "title": "Tren Total Pengguna Bulanan",
   "type": "bargauge",
   "description": "Selama tahun 2017\n(Biru = diatas rata-rata)",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "org" } },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(January) AS 'JAN' FROM wifiBandung; "
    },
    {
     "rawSql": "SELECT SUM(February) AS 'FEB' FROM wifiBandung; "
    },
    {
     "rawSql": "SELECT SUM(March) AS 'MAR' FROM wifiBandung; "
    },
    {
     "rawSql": "SELECT SUM(April) AS 'APR' FROM wifiBandung; "
    },
    {
     "rawSql": "SELECT SUM(May) AS 'MAY' FROM wifiBandung; "
    },
    {
     "rawSql": "SELECT SUM(June) AS 'JUN' FROM wifiBandung; "
    },
    {
     "rawSql": "SELECT SUM(July) AS 'JUL' FROM wifiBandung; "
    },
    {
     "rawSql": "SELECT SUM(August) AS 'AUG' FROM wifiBandung; "
    },
    {
     "rawSql": "SELECT SUM(September) AS 'SEP' FROM wifiBandung; "
    },
    {
     "rawSql": "SELECT SUM(October) AS 'OCT' FROM wifiBandung; "
    },
    {
     "rawSql": "SELECT SUM(November) AS 'NOV' FROM wifiBandung; "
    },
    {
     "rawSql": "SELECT SUM(December) AS 'DES' FROM wifiBandung; "
    }
   ]
  }
 ]
}