version: "3"
networks:
    net:
    
services:
    mysql:
        build: './database-mysql'
        restart: always
        expose:
            - '3306'
        networks:
            net:
                aliases:
                    - mysql
        
    grafana:
        build: './visualization-grafana'
        restart: always
        ports:
            - '3000:3000'
        networks:
            net:
                aliases:
                    - grafana